### ISSUE TITLE
Progress tracking.

### ISSUE THREAD

**Issue by sustained** [vuejs-sv/vuejs.org#3]
* [x] **[/themes/vue/layout/](https://github.com/vuejs-sv/vuejs.org/tree/master/themes/vue/layout)**
  * [x] index.ejs
  * [x] page.ejs
  * [x] post.ejs
  * [x] search-page.ejs
  * [x] sponsors-page.ejs
  * [x] **[/partials/](https://github.com/vuejs-sv/vuejs.org/tree/master/themes/vue/layout/partials)**
    * [x] conf.ejs
    * [x] ecosystem_dropdown.ejs
    * [x] language_dropdown.ejs
    * [x] learn_dropdown.ejs
    * [x] main_menu.ejs
    * [x] platinum_sponsors.ejs
    * [x] sidebar.ejs
    * [x] sponsors.ejs
    * [x] sponsors_sidebar.ejs
    * [x] support_vue_dropdown.ejs
    * [x] toc.ejs

* [ ] **[/src/v2/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2)**
  * [ ] **[/api/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/api)**
    * [ ] index.md
  * [ ] **[/cookbook/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/cookbook)**
    * [ ] adding-instance-properties.md
    * [ ] avoiding-memory-leaks.md
    * [ ] client-side-storage.md
    * [ ] creating-custom-scroll-directives.md
    * [ ] debugging-in-vscode.md
    * [ ] dockerize-vuejs-app.md
    * [ ] editable-svg-icons.md
    * [ ] form-validation.md
    * [ ] index.md
    * [ ] packaging-sfc-for-npm.md
    * [ ] practical-use-of-scoped-slots.md
    * [ ] serverless-blog.md
    * [ ] unit-testing-vue-components.md
    * [ ] using-axios-to-consume-apis.md
  * [ ] **[/examples/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/examples)**
    * [ ] commits.md
    * [ ] deepstream.md
    * [ ] elastic-header.md
    * [ ] firebase.md
    * [ ] grid-component.md
    * [ ] hackernews.md
    * [ ] index.md
    * [ ] modal.md
    * [ ] select2.md
    * [ ] svg.md
    * [ ] themes.md
    * [ ] todomvc.md
    * [ ] tree-view.md
  * [ ] **[/guide/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/guide)**
    * [ ] class-and-style.md
    * [ ] comparison.md
    * [ ] components-custom-events.md
    * [ ] components-dynamic-async.md
    * [ ] components-edge-cases.md
    * [ ] components-props.md
    * [ ] components-registration.md
    * [ ] components-slots.md
    * [ ] components.md
    * [ ] computed.md
    * [ ] conditional.md
    * [ ] custom-directive.md
    * [ ] deployment.md
    * [ ] events.md
    * [ ] filters.md
    * [ ] forms.md
    * [ ] index.md
    * [ ] installation.md
    * [ ] instance.md
    * [ ] join.md
    * [ ] list.md
    * [ ] migration-vue-router.md
    * [ ] migration-vuex.md
    * [ ] migration.md
    * [ ] mixins.md
    * [ ] plugins.md
    * [ ] reactivity.md
    * [ ] render-function.md
    * [ ] routing.md
    * [ ] single-file-components.md
    * [ ] ssr.md
    * [ ] state-management.md
    * [ ] syntax.md
    * [ ] team.md
    * [ ] transitioning-state.md
    * [ ] transitions.md
    * [ ] typescript.md
    * [ ] unit-testing.md
  * [x] **[/search/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/search)**
    * [x] index.md
  * [ ] **[/style-guide/](https://github.com/vuejs-sv/vuejs.org/tree/master/src/v2/style-guide)**
    * [ ] index.md
